---

- name: Init Postgres
  command: /usr/pgsql-12/bin/postgresql-12-setup initdb
  args:
    creates: /var/lib/pgsql/12/data/PG_VERSION

- name: Configure listen address
  lineinfile:
    dest: /var/lib/pgsql/12/data/postgresql.conf
    regexp: "^#listen_addresses ="
    line: "listen_addresses = '*'"
  notify: restart postgres

- name: Configure hba listen address
  lineinfile:
    dest: /var/lib/pgsql/12/data/pg_hba.conf
    line: "host all all 0.0.0.0/0 md5"
  notify: restart postgres
